# mosquitto.conf
# MQTT broker configuration for SAE 23

listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous true

persistence true
persistence_location /mosquitto/data

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all

# Bridge IUT: port 8883 TLS + student
connection bridge-iut
address mqtt.iut-blagnac.fr:8883
bridge_cafile /etc/ssl/certs/ca-certificates.crt
bridge_insecure true
bridge_tls_version tlsv1.2
remote_username student
remote_password student
remote_clientid sae23-bridge
# AM107 real sensors (30 rooms, all buildings)
topic sensors/AM107/by-room/# in 0
start_type automatic
try_private false
